### ISSUE TITLE
Add easy paintfunction

### ISSUE THREAD

**Issue by MKleinSB** [r00b1nh00d/pxt-max7219#1]
you can add (and optimise) this code to get an easy paintfunction. Rotation is not supported yet.

![grafik](https://user-images.githubusercontent.com/37311672/115743051-94fb1380-a391-11eb-8e98-c94eb7481904.png)

    //% block=Image 8x8"
    //% imageLiteral=1
    //% imageLiteralColumns=8
    //% imageLiteralRows=8
    //% shim=images::createImage
    //% group="4. Set custom LED pattern on matrixs"
    export function matrix8x8(i: string): Image {
        const im = <Image><any>i;
        return im
    }

    //% block="write image to Matrix %index %im=variables_get(image)"
    //% index.defl=1 index.min=1 index.max=7 group="4. Set custom LED pattern on matrixs"
    export function writeImage2matrix (index:number, im: Image) {
     let line=0   
    for (let y = 0; y <= im.height() - 1; y++) {
        for (let x = 0; x <= im.width() - 1; x++) {
            if (im.pixel(x, y)) {
                line=(line << 1) + 1
                 } else {
                 line=(line << 1)  
                }
                _registerForOne(_DIGIT[im.height()-1-y], line, _matrixNum-index)
            }
            line=0
        }
    }

**Comment by r00b1nh00d** [comment]
Thanks for the comment. The Option is added.
